"""The HTTP API (FastAPI): what a website, mobile app or another service calls.

  GET  /health   - the process is up (for the load balancer / container platform: restart it if this fails)
  GET  /ready    - models are loaded and requests can be served (send traffic only when this says yes)
  POST /stars    - predicted star rating (1.0-5.0) for up to 32 review texts, ONNX INT8 model
  POST /search   - hybrid search over the reviews (Part 7)
  POST /chat     - one message to the chatbot (Part 12); the conversation is kept per session_id
  /ui            - the Gradio web page (serving/ui.py)
  /docs          - interactive API documentation, generated by FastAPI from the request/response models

Production choices in this file:
  * Models are loaded once at startup (lifespan), not per request; /ready reports when they are.
  * Every request and response has a pydantic model: wrong or oversized input gets a clear 422 error, never a crash.
  * One lock around the chatbot: the local LLM runs one generation at a time. (At scale the LLM is a separate,
    batching server such as vLLM or a hosted API, and this service scales out with more copies.)
  * Each response carries an X-Request-ID and is logged with its latency (no request text: reviews and chats can
    contain personal data).

  uvicorn reviewsense.serving.api:app --port 8000          # then open http://localhost:8000/docs or /ui
"""
from __future__ import annotations

import logging
import threading
import time
import uuid
from contextlib import asynccontextmanager
from dataclasses import dataclass

from fastapi import FastAPI, HTTPException, Request
from pydantic import BaseModel, Field

from ..config import get_settings

log = logging.getLogger("reviewsense.api")
MAX_TEXT = get_settings().max_text_length


# ---- request and response shapes (validated by pydantic, documented at /docs)
class StarsRequest(BaseModel):
    texts: list[str] = Field(min_length=1, max_length=32, description="review texts (at most 32)")


class StarsResponse(BaseModel):
    stars: list[float]


class SearchRequest(BaseModel):
    query: str = Field(min_length=1, max_length=500)
    business: str | None = None
    k: int = Field(default=5, ge=1, le=20)


class SearchHit(BaseModel):
    text: str
    business: str
    review_id: str
    score: float | None


class SearchResponse(BaseModel):
    corrected: str | None
    results: list[SearchHit]


class ChatRequest(BaseModel):
    session_id: str = Field(min_length=1, max_length=100)
    message: str = Field(min_length=1, max_length=2000)


class ChatResponse(BaseModel):
    answer: str
    action: str | None
    blocked: str | None
    sources: list[dict]


@dataclass
class Components:
    """Everything the endpoints use. Built from real models at startup, or from stand-ins in tests."""
    stars: object
    search: object
    chatbot: object | None = None


def load_components() -> Components:
    from ..data import load_reviews
    from ..search.engine import SearchEngine
    from .onnx_model import OnnxStarModel

    settings = get_settings()
    chatbot = None
    if settings.serve_chat:
        from ..chat.dialog import Chatbot
        from ..safety.safe_assistant import SafeAssistant
        chatbot = Chatbot(SafeAssistant(load_reviews()))
    return Components(stars=OnnxStarModel(), search=SearchEngine(load_reviews()), chatbot=chatbot)


def create_app(components: Components | None = None) -> FastAPI:
    """`components` given (tests): use them. Not given: load the real models when the server starts."""

    @asynccontextmanager
    async def lifespan(app: FastAPI):
        app.state.components = components or load_components()
        log.info("models loaded, ready")
        yield

    app = FastAPI(title="ReviewSense API", version="1.0", lifespan=lifespan)
    chat_lock = threading.Lock()

    def parts(request: Request) -> Components:
        loaded = getattr(request.app.state, "components", None)
        if loaded is None:
            raise HTTPException(status_code=503, detail="models are still loading")
        return loaded

    @app.middleware("http")
    async def request_log(request: Request, call_next):
        request_id = request.headers.get("X-Request-ID", uuid.uuid4().hex[:12])
        start = time.perf_counter()
        response = await call_next(request)
        response.headers["X-Request-ID"] = request_id
        log.info("%s %s %s %.0f ms id=%s", request.method, request.url.path, response.status_code,
                 (time.perf_counter() - start) * 1000, request_id)
        return response

    @app.get("/health")
    def health() -> dict:
        return {"status": "ok"}

    @app.get("/ready")
    def ready(request: Request) -> dict:
        loaded = parts(request)
        return {"status": "ready", "chat": loaded.chatbot is not None}

    @app.post("/stars", response_model=StarsResponse)
    def stars(body: StarsRequest, request: Request) -> StarsResponse:
        if any(len(text) > MAX_TEXT for text in body.texts):
            raise HTTPException(status_code=422, detail=f"each text may have at most {MAX_TEXT} characters")
        return StarsResponse(stars=parts(request).stars.stars(body.texts))

    @app.post("/search", response_model=SearchResponse)
    def search(body: SearchRequest, request: Request) -> SearchResponse:
        result = parts(request).search.search(body.query, k=body.k, business=body.business)
        hits = [SearchHit(text=hit["text"], business=hit["business"], review_id=hit["review_id"], score=hit["score"])
                for hit in result["results"]]
        return SearchResponse(corrected=result["corrected"], results=hits)

    @app.post("/chat", response_model=ChatResponse)
    def chat(body: ChatRequest, request: Request) -> ChatResponse:
        chatbot = parts(request).chatbot
        if chatbot is None:
            raise HTTPException(status_code=503, detail="chat is switched off (REVIEWSENSE_SERVE_CHAT=false)")
        with chat_lock:
            result = chatbot.ask(body.session_id, body.message)
        return ChatResponse(answer=result["answer"], action=result.get("action"), blocked=result.get("blocked"),
                            sources=result.get("sources", []))

    return app


def build_app() -> FastAPI:
    """The served app: the API plus the Gradio page at /ui."""
    import gradio

    from .ui import build_ui

    app = create_app()
    return gradio.mount_gradio_app(app, build_ui(app), path="/ui")


app = build_app()        # what uvicorn serves: uvicorn reviewsense.serving.api:app
